"""add job_leads table

Revision ID: 473b757cc096
Revises: 4d6427720beb
Create Date: 2026-07-11 14:43:25.589328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '473b757cc096'
down_revision: Union[str, None] = '4d6427720beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('employer', sa.String(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('fit_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'seen', 'applied', 'dismissed', name='leadstatus'), nullable=False),
    sa.Column('found_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'url', name='uq_job_leads_profile_url')
    )
    op.create_index(op.f('ix_job_leads_profile_id'), 'job_leads', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_leads_profile_id'), table_name='job_leads')
    op.drop_table('job_leads')
    sa.Enum(name='leadstatus').drop(op.get_bind())
    # ### end Alembic commands ###
