"""add_foreign_key_indexes

Revision ID: 5bd31681f422
Revises: d531947b9bb7
Create Date: 2026-06-24 15:05:18.770753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd31681f422'
down_revision: Union[str, None] = 'd531947b9bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_target_roles_profile_id'), 'target_roles', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_roles_profile_id'), table_name='target_roles')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    # ### end Alembic commands ###
