"""initial

Revision ID: d531947b9bb7
Revises: None
Create Date: 2026-06-23 16:11:09.368200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd531947b9bb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('temple_email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('student', 'counselor', 'admin', name='userrole'), nullable=False),
    sa.Column('llm_generation_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temple_email')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('degree_level', sa.Enum('undergrad', 'grad', 'phd', name='degreelevel'), nullable=True),
    sa.Column('major_program', sa.String(), nullable=True),
    sa.Column('expected_graduation', sa.Date(), nullable=True),
    sa.Column('track', sa.Enum('industry', 'academia', 'government', 'undecided', name='track'), nullable=False),
    sa.Column('is_first_gen', sa.Boolean(), nullable=True),
    sa.Column('resume_doc_id', sa.String(), nullable=True),
    sa.Column('linkedin_doc_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_roles')
    op.drop_table('profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
